// <auto-generated />
using System;
using Booking.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Model.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Booking.Model.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = 3,
                            Description = "It is yoga class",
                            EndTime = new DateTime(2023, 11, 18, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8781),
                            Fee = 2,
                            Name = "Yoga class",
                            StartTime = new DateTime(2023, 11, 11, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8772)
                        },
                        new
                        {
                            Id = 2,
                            Country = 1,
                            Description = "It is golf class",
                            EndTime = new DateTime(2023, 11, 18, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8786),
                            Fee = 2,
                            Name = "Golf class",
                            StartTime = new DateTime(2023, 11, 11, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8786)
                        },
                        new
                        {
                            Id = 3,
                            Country = 0,
                            Description = "It is luagage class",
                            EndTime = new DateTime(2023, 11, 18, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8788),
                            Fee = 2,
                            Name = "Language class",
                            StartTime = new DateTime(2023, 11, 11, 17, 11, 19, 183, DateTimeKind.Local).AddTicks(8787)
                        });
                });

            modelBuilder.Entity("Booking.Model.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Booking.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfCredits")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "eihninphyu1996@gmail.com",
                            NumberOfCredits = 10,
                            Password = "12345",
                            PhoneNumber = "09245555775"
                        });
                });

            modelBuilder.Entity("PackageUser", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("PackagesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PackageUser");
                });

            modelBuilder.Entity("Booking.Model.Schedule", b =>
                {
                    b.HasOne("Booking.Model.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Model.User", "User")
                        .WithMany("Schedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PackageUser", b =>
                {
                    b.HasOne("Booking.Model.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Model.User", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
